from src.utils import *
from src.metadata import *


## ALIGN ANCHORS
def get_xy_anchors_for_one_day(anchors_dir, perm=None):
    """Load anchors from image file and return x,y coordinates of four anchors.

    Args:
        anchors_dir (str): to load black and white image
        perm (list or None, optional): a list of four integers to permute the
            order of anchors.

    Returns:
        xy_sort (np.ndarray): x,y coordinates of four anchors, shape (4,2)

    Example:
        Below rotates the anchors by 90 degrees::

            anchors_dir = "data/anchors_all_mice/cam_mouse6_sess2.jpg"
            perm = [1,3,0,2]
    """
    # convert image to array
    img = Image.open(anchors_dir)
    if len(np.array(img).shape) == 3:  # RBG
        img_arr = np.array(img).sum(axis=-1)
    else:
        img_arr = np.array(img)  # black and white
    mask = img_arr < img_arr.max() / 2

    # extract blobs
    labels, count = label(mask, connectivity=1, return_num=True)
    blobs = np.array(regionprops(labels))
    bboxes = np.array([x.bbox for x in blobs])
    xy_anchors = np.stack(
        [bboxes[:, [1, 3]].sum(1) / 2, bboxes[:, [0, 2]].sum(1) / 2], axis=-1
    )

    # sort 4 anchors
    x_mid, y_mid = [x / 2 for x in mask.shape]
    bool_xy_anchors = sorted(
        [((x >= x_mid, y >= y_mid), (x, y)) for x, y in xy_anchors]
    )
    xy_sort = np.float32(
        [y for x, y in bool_xy_anchors]
    )  # float32 for compatibility with opencv

    # permute anchors if needed
    if perm is not None:
        xy_sort = xy_sort[perm]
    return xy_sort


## PROCESS ANNOTATED TILES
def get_hexagon_dir_list(load_dir):
    """Get the list of directory to hexagon images, sorted by file name.

    Args:
        load_dir (str): directory to load hexagon images; e.g., ``load_dir = 'mouse10_sess6_annotated_tiles'``

    Returns:
        hexagon_dir_sort (list of str): sorted list of hexagon image paths
    """
    hexagon_dir_list = list(load_dir.glob("*.png"))

    # sort by file name
    idx_sort = np.argsort(
        [eval(re.findall(r"\d+", str(x)[-10:])[0]) for x in hexagon_dir_list]
    )
    hexagon_dir_sort = [hexagon_dir_list[i] for i in idx_sort]
    return hexagon_dir_sort


def gen_one_dff_hexagon(hexagon_dir, rgb_sum_th=255 * 3):
    """Generate a DataFrame of pixel coordinates for a hexagon image where pixel values are below a threshold.

    NOTE:
        ``rgb_sum_th = 255*3`` for white background

    Args:
        hexagon_dir (str): path to the hexagon image file
        rgb_sum_th (int, optional): threshold for the sum of RGB values to consider a pixel part of the hexagon. Defaults to 255*3.

    Returns:
        dff (pd.DataFrame): DataFrame containing pixel coordinates of one hexagon
        (x_mean, y_mean) (tuple): mean x and y coordinates of the hexagon
    """
    a = Image.open(hexagon_dir)
    dff = pd.DataFrame(
        (
            (x, y)
            for x in range(0, a.width, 20)
            for y in range(0, a.height, 20)
            if np.sum(a.getpixel((x, y))) < rgb_sum_th
        ),
        columns=("x", "y"),
    )  # every 5 pixels
    x_mean = dff["x"].values.mean()
    y_mean = dff["y"].values.mean()
    return dff, (x_mean, y_mean)


def gen_df_tile(dff_list, xy_mean_list):
    """This function generates a single ``df`` that contains all tile data generated by :func:`gen_one_dff_hexagon`.

    Args:
        dff_list (list of pd.DataFrame): list of pd.DataFrame, each df is a hexagon
        xy_mean_list (list of tuple): list of ``(x,y)`` tuples, each tuple is the mean x,y of the hexagon

    Returns:
        df (pd.DataFrame): stores all pixels for each tile
        df_mean (pd.DataFrame): stores the centroids of each tile
    """
    # df tile centroids
    df_mean = pd.DataFrame(xy_mean_list, columns=["x", "y"])

    # df tile pixels
    dff_list_1 = []
    for tile_id, dff in enumerate(dff_list):
        dff["tile_id"] = tile_id
        dff_list_1.append(dff)
    df = pd.concat(dff_list_1)
    df.index = range(len(df))
    return df, df_mean
